### PR TITLE
Directory check integration

### PR DESCRIPTION
**Pull request by kindlyseth**
This pull request adds support for the standard directory check integration, http://docs.datadoghq.com/integrations/directory/ .

### CODE REVIEW

**Comment by statik** [comment]
This looks great, I'd love to start using this on several of my datadog installations.

**Comment by miketheman** [comment]
@kindlyseth Would you consider porting the Kitchen test to a Spec test? See [here](https://github.com/DataDog/chef-datadog/pull/295) for an example.

Specs are much "cheaper" to run overall, and validate template renderings just as much as the kitchen tests do. My hope is that we'll port over all existing kitchen tests to specs, and some of the effort has started, so I'd like to not introduce more if possible.

**Comment by kindlyseth** [comment]
Yep, I'll try to find time early next week.

**Comment by kindlyseth** [comment]
@miketheman, I think the CircleCI check is not my error. Looks like it might need a version bump that's probably been done on master, but I didn't know if it was worth it to rebase and do a new PR.

**Comment by miketheman** [comment]
@kindlyseth Thanks! I've rebased and squashed to a single commit here: https://github.com/DataDog/chef-datadog/compare/kindlyops-directory?expand=1

If it passes CI, then it's ripe for merge, and I'll take it from there.

Thanks!

**Comment by miketheman** [comment]
Thanks!

**Comment by kindlyseth** [comment]
Thank you!

**Pull request closed without merging**
