### PR TITLE
Adding a datadog::ssh_check recipe to leverage SSH checks

### PR DESCRIPTION
**Pull request by wk8**
With the corresponding kitchen test.

### CODE REVIEW

**Comment by wk8** [comment]
@darron @miketheman: any chance you could have a look at this? I'd hate for our prod DD cookbook to diverge from yours... Thanks!

**Comment by miketheman** [comment]
@wk8 We're planning a bunch of reviews in the coming weeks.

**Comment by wk8** [comment]
@miketheman thanks! :)

**Comment by wk8** [comment]
Thanks!

**Pull request merged**
