### PR TITLE
Added dns_check support

### PR DESCRIPTION
**Pull request by nickmarden**

### CODE REVIEW

**Comment by nickmarden** [comment]
@miketheman Thanks for the `needs spec test` - I was unclear that individual recipes should be added for individual templates, but I followed my nose and came up with something that seems to have coverage and look like all of the other spec-ified recipes.

**Comment by miketheman** [comment]
Hi @nickmarden !
Thanks - the spec looks great, it's failing to run due to a linter violation - see https://travis-ci.org/DataDog/chef-datadog/builds/123973389#L254

**Comment by nickmarden** [comment]
Thanks @miketheman - fixed and re-running CI now.

**Comment by miketheman** [comment]
Thanks! Added to the merge queue.

**Pull request merged**
