### PR TITLE
Add recipes for http_check and tcp_check

### PR DESCRIPTION
**Pull request by mtougeron**
Add a recipe for http_check and tcp_check to fill out the respective templates. This addresses issue #110

### CODE REVIEW

**Comment by miketheman** [comment]
@mtougeron thanks for continuing to work through this.

In https://github.com/DataDog/chef-datadog/pull/153#issuecomment-68599421 I mentioned that we no longer support the `@notify` syntax - I've been digging, trying to find a warning message to link to, but that hasn't been produced client-side yet.

Also, as I was writing this, #178 popped up. 
I think  the combination of these two styles is what I was going for.

**Comment by mtougeron** [comment]
ack, sorry about missing #153#issuecomment-68599421 fixing it now

**Comment by mtougeron** [comment]
@miketheman do you know which route you want to go with this PR vs #178 & #179? I need to make a similar set of changes for the 'process' check/template.

**Comment by mtougeron** [comment]
@miketheman Any updates on this & PR #181? I just don't want to end up in a situation again where I have to refactor a 4th time due to changes on your end. :) Thanks.

**Comment by mtougeron** [comment]
@miketheman ping? any update on this?

**Comment by miketheman** [comment]
@mtougeron sorry for the delay. I've scheduled a time on my calendar for tomorrow to actively work on this particular branch and pull. I might do some rebasing and such.

**Comment by mtougeron** [comment]
Thanks. No worries about the delay, I just didn't want to have to redo it a 3rd time. :)

**Comment by mtougeron** [comment]
@miketheman any update on this? I'd really like to see this and PR #181 included so that I don't have to maintain a forked version of this cookbook. Thanks, Mike

**Comment by mtougeron** [comment]
@miketheman any update on this? Thanks, Mike

**Comment by mtougeron** [comment]
Pushed an update to the `.kitchen.yml` to resolve conflicts from a recent merge

**Comment by miketheman** [comment]
Thanks for bearing with me! I rebased a bit and used the new template structure, but we're finally merged to master with the new recipes.

**Comment by mtougeron** [comment]
Thanks!

**Pull request closed without merging**
