### PR TITLE
added windows agent installation support

### PR DESCRIPTION
**Pull request by EasyAsABC123**
This adds the ability to install the latest (or locally archieved) datadog windows agent.

### CODE REVIEW

**Comment by EasyAsABC123** [comment]
@miketheman can I get an estimate on timeline for this pull request?  the "conflict" is pretty simple to resolve.  The dd-agent becomes a switch statement which then calls the current dd-agent renamed dd-agent-linux if it isn't a windows agent or calls the new dd-agent-windows otherwise.

**Comment by remh** [comment]
Thanks @EasyAsABC123 !

I think you should remove support of Windows XP which is EOLed and Windows server 2003 which will be EOLed in 3 months (http://chiron.gb2n.org/datadog/eolgoodness/) and for which the latest Agent release will be 5.2.0 (there won't be any further release of the Agent for Windows Server 2003).

It would simplify your pull request as you'll be able to get rid of your older_than_windows2003r2 helper.

**Comment by EasyAsABC123** [comment]
@remh removed helper and older windows support.

**Comment by miketheman** [comment]
Closed via #210.

**Pull request closed without merging**
