### PR TITLE
If the 'docker' group exists, append the 'dd-agent' user to it

### PR DESCRIPTION
**Pull request by jvrplmlmn**
Closes https://github.com/DataDog/chef-datadog/issues/363

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
@olivielpeau I think that you're an owner of this repository.

**Comment by jvrplmlmn** [comment]
CircleCI seems to have failed for an issue non related to this change. Can you rebuild it or do I need to rewrite the commit to trigger it again?

**Comment by olivielpeau** [comment]
@jvrplmlmn I've rebuilt the CircleCI job, the tests seem a little flaky there, I'll look into them if the issue persists.

I'll merge as soon as the tests pass. Thanks!

**Comment by jvrplmlmn** [comment]
@olivielpeau Tests are now passing! Any chance that we could have a `2.6.1` version released? Otherwise I'll wait to `2.7.0`.

**Comment by olivielpeau** [comment]
@jvrplmlmn thanks, merging!

Since this is more an improvement than a bugfix I'd rather release this with the next minor, `2.7.0`, once we have enough features ready. You can definitely use your own fork of the cookbook until then, hope that's not too much of a hassle for you.

**Pull request merged**
