### PR TITLE
chef-datadog-809 Support cookbook renaming

### LINKED ISSUE #809: Support cookbook renaming
In many places there is `include_recipe` with reference to `datadog` cookbook.
To support cookbook renaming they should use `::<recipe>`

### PR DESCRIPTION
**Pull request by lchayoun**
resolves #809

### CODE REVIEW

**Review by cswatt — APPROVED** [review]
approved for docs.

**Review by mx-psi — COMMENTED** [review]
@lchayoun Thanks for the PR! Before we merge this PR you will need to take a look at CI and fix the errors

**Comment by lchayoun** [comment]
@mx-psi All failures now are:
`Cookbook 'yum' version '7.0.0' depends on chef version [">= 15.3"], but the running chef version is 14.10.9`

Any idea?

**Comment by mx-psi** [comment]
@lchayoun can you merge main into your branch? #811 should fix it

**Review by mx-psi — APPROVED** [review]
Thank you again! CI is passing (except for a job that is also failing on `main`) so I am merging 🎉

**Pull request merged**
