### PR TITLE
add encrypted databag support

### PR DESCRIPTION
**Pull request by shortdudey123**
Updated old pull request to the newest head revision (https://github.com/DataDog/chef-datadog/pull/99)

Solves https://github.com/DataDog/chef-datadog/issues/96

### CODE REVIEW

**Comment by shortdudey123** [comment]
@miketheman that assumes the infrastructure is already running Chef 12.

rm does not exist in Cheff 11 and prior
http://www.rubydoc.info/gems/chef/11.16.4/Chef/Node/Attribute

**Comment by ranjib** [comment]
@miketheman may be this is not the right approach, but setting a secret as raw node attribute, which is searchable by all other nodes (or any non-admin chef api client) is really a security hole. Not only we should address that (i.e. offer any other mechanism that does not leak the password), we should also declare all the resources (like template) that uses the creds as sensitive.

**Comment by miketheman** [comment]
Reviewed again. We won't fix this right now, and will explore other security measures for this in the next major release.

**Comment by shortdudey123** [comment]
no problem, i will keep the branch around in case you want to use it to improve security in the future :)

**Pull request closed without merging**
