### PR TITLE
Old windows cookbook does not support the `returns` attribute.

### PR DESCRIPTION
**Pull request by remeh**
We advice to use `windows ~> 1.38.0` for some setup, but this cookbook version does not  support the `returns` attribute yet.

### CODE REVIEW

**Comment by truthbk** [comment]
Tests are failing though!

**Comment by olivielpeau** [comment]
Does it still make sense to advise users to use `windows ~> 1.38.0` with the future 3.x versions of the cookbook ? 🤔Shouldn't we not have any dependency on the `windows` cookbook anymore?

**Comment by remeh** [comment]
@olivielpeau You're right we don't have this dep anymore, I've tested on 12/13/14 and it works correctly without the `windows` cookbook.
I'll create a PR to remove the advice in the README + comment this fix.

**Comment by remeh** [comment]
Done in https://github.com/DataDog/chef-datadog/pull/617

**Pull request merged**
