### PR TITLE
Adding support for list of datadog tags in v6 configuration file

### LINKED ISSUE #556: Add Back Support For Tags as List In v6 datadog.yaml File
The V5 datadog.config file allowed for the tags variable to be passed in as a list object.

https://github.com/DataDog/chef-datadog/blob/971791e7fba30e072d3f05edc6a5523155275b1c/templates/default/datadog.conf.erb#L24

This is no longer supported in V6.  It will only accept a hash https://github.com/DataDog/chef-datadog/blob/971791e7fba30e072d3f05edc6a5523155275b1c/templates/default/datadog.yaml.erb#L26  or string https://github.com/DataDog/chef-datadog/blob/971791e7fba30e072d3f05edc6a5523155275b1c/templates/default/datadog.yaml.erb#L29.  This causes issues for those migrating from v5 to v6 with an existing set of Chef roles that use lists for defining data dog tags.

Add support for a data dog tags attribute list object.

### PR DESCRIPTION
**Pull request by skarlupka**
Fixes #556

### CODE REVIEW

**Comment by tschroeder-zendesk** [comment]
Any estimate on when this might get merged?

**Comment by remeh** [comment]
Hey @skarlupka , thank you for your contribution!
I've investigated this and indeed we have a different behavior between the Agent 5 and Agent 6 while using a list of tags.

Before merging your pull-request I would like to add some commits to have the exact same behavior between Agent 5 and Agent 6 (the list of tags injected in the Agent 5 configuration is working but not 100% correct).

Could I ask you to tick the box letting me to push commits in your PR? Thank you.

**Comment by skarlupka** [comment]
Hello @remeh!

The "Allow edits from maintainers" is checked in the PR.  Let me know if there is anything else I need to do.

**Comment by remeh** [comment]
Thank you @skarlupka 

I've added a condition to correctly handle the list of tags in the Agent 5 configuration + I've slighty changed your PR to stay with `respond_to` tests to be consistent with the rest of the repo.

**Comment by remeh** [comment]
Thanks again for your contribution @skarlupka!

@tschroeder-zendesk I'm merging this to master now and it'll be part of release `2.17.0`

**Pull request merged**
