### PR TITLE
New http_check recipe+template

### PR DESCRIPTION
**Pull request by chrissnell**
A new recipe and template for http_check.   Template uses the Ruby->JSON->YAML data structure conversion a la the JMX check recipe.

### CODE REVIEW

**Comment by chrissnell** [comment]
Fixed the Travis build error.

**Comment by chrissnell** [comment]
@miketheman I much prefer your new style of YAML building using the Ruby data structure.   If the  PR from @mtougeron is what you want to roll with, you won't hurt my feelings but we (Revinate) definitely love your new style of config and would prefer to use it.

**Comment by miketheman** [comment]
@chrissnell I'm a big fan as well - as you can see, there's a comment on that one.

I guess "whomever can get the code & tests into place first" wins? /cc: @mtougeron

**Comment by mtougeron** [comment]
ready... set... race!! haha. but in all seriousness, I'm updating PR 177 now.

**Comment by chrissnell** [comment]
You want TESTS?  I think @mtougeron is going to win this one.  :)

**Comment by miketheman** [comment]
Thanks for bearing with me - I rebased and reordered a touch, but we're not merged to master along with the other changesets.

**Pull request closed without merging**
