### PR TITLE
Add a recipe for http_check and tcp_check

### PR DESCRIPTION
**Pull request by mtougeron**
Add a recipe for http_check and tcp_check to fill out the respective templates. This addresses issue #110

### CODE REVIEW

**Comment by miketheman** [comment]
Hi @mtougeron ,

Thanks for your continued efforts here.

Some things have changed since I last read through the PR:

- The Vagrantfile was dropped completely in favor of test-kitchen - this may explain the merge conflict.

- We no longer recommend use of the `notify` config in favor of using actual Network Check logic in the Datadog Monitors configuration. See here for latest config examples: https://github.com/DataDog/dd-agent/blob/master/conf.d/http_check.yaml.example
This simplifies the init_config section in both the recipes and templates.

- I recently pushed a change to the JMX check template, which allows the end user to build up an Array of Instances (in Hash format) that express the configuration without needing to add spacing, if/else statements for every possible flag. I think this simplifies the lifecycle for options that are added to the Agent, as they can be used immediately without a cookbook update. See c2e0dbfd2ef15d1f229aa6f7df2f54df399776e5 for examples of how that's done, with tests included.

If you'd like to continue to refactor this, I'd really appreciate it - maybe a rebase and squash might be in order, as the tests have changed a bit too.

Best,
-M

**Comment by mtougeron** [comment]
Doh! I'll take a look this week.

**Comment by miketheman** [comment]
@mtougeron any news? If not, I'll scrub it, use some parts and get the latest stuff in.

**Comment by mtougeron** [comment]
ack, sorry for the delay. I'll work on it this morning.

**Comment by miketheman** [comment]
No worries. If you're following along, some things were renamed for clarity, and a lot of the testing has been updated. See most recently the datadog_activemq and datadog_haproxy test suites.

**Comment by mtougeron** [comment]
@miketheman I've made the changes but I'm having trouble testing them. The box file that test-kitchen is trying to download doesn't exist. It is trying to download https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.5_provisionerless.box 

Do you know anything about that? I've tried other recipes than mine and they also have the same issue.

**Comment by miketheman** [comment]
I've seen that - there's a minor change in the URL that I have staged locally and haven't pushed yet (as well as many other .kitchen.yml updates).

https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.5_provisionerless.box =>
https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_provisionerless.box

**Comment by mtougeron** [comment]
I'm still getting a 404 on that new url too.

**Comment by miketheman** [comment]
My bad, forgot the branding: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

**Comment by mtougeron** [comment]
ya! thanks. :)

**Comment by mtougeron** [comment]
ugh, I did something wrong with the rebase, refactor. going to open a new PR. sorry.

**Comment by mtougeron** [comment]
@miketheman created PR #177 instead of this one.

**Pull request closed without merging**
