### PR TITLE
Add support for multiple tags via key/value

### PR DESCRIPTION
**Pull request by lightpriest**
A new pull request (previous is #183) without a version change and with a more strict test for Hash implementation.

---

Enables setting tags from different attribute levels, backward compatible.

Suppose you have role A which acts on two environments B and C.
This patch enables setting this on the role:

    {
      "datadog": {
        "tags": {
          "cluster": "A"
        }
      }
    }

And these on the different environments:

    {
      "datadog": {
        "tags": {
          "environment": "B"
        }
      }
    }

    {
      "datadog": {
        "tags": {
          "environment": "C"
        }
      }
    }

Will result in datadog.conf having `tags: cluster:A,environment:B` and `tags: cluster:A,environment:C` respectively. String version of the tags should still work. To remove a tag in a higher precedence level, set it to an empty string.

This is also reported in #170.

### CODE REVIEW

**Comment by miketheman** [comment]
@lightpriest Getting back to this feature now. Looks like it can't be merged - there might be a conflict in the datadog.conf somewhere.

Also, is there any tests you might write with ChefSpec to validate the template outcome of passing in the tags attribute?

**Comment by lightpriest** [comment]
@miketheman I added a spec for this, imitating the structure of the other specs. I also tried to add a commit that would fix the merge conflict, but I guess it wasn't enough.

The conflict is in a comment section in `attributes/default.rb` and after my commit I think it should be even simpler to merge. If that's a problem, I'll open another pull-request.

**Comment by jslusher** [comment]
+1 for this!

**Comment by miketheman** [comment]
Closing, as superseded with #296 

Thanks for the contribution!

**Pull request closed without merging**
