### PR TITLE
issue 287 - dd-agent doesn't have authorization to run the agent's co…

### PR DESCRIPTION
**Pull request by BrentOnRails**
…mmands
- allow NOPASSWD /usr/bin via attribute
- configure sudoers command per directory instance

### CODE REVIEW

**Comment by BrentOnRails** [comment]
> Action failed: chef gem install kitchen-docker -v '~> 2.3.0'

**Comment by miketheman** [comment]
@BrentOnRails The CI failure is due to this commit not being from a current `master` - can you rebase and push again?

**Comment by BrentOnRails** [comment]
@miketheman thanks. Rebased.

**Comment by degemer** [comment]
Hey @BrentOnRails, we're going to release soon 2.7.0 (this week), so I'm going to move this PR to the 2.8.0 milestone. Sorry for the short notice!

**Comment by degemer** [comment]
Merged in https://github.com/DataDog/chef-datadog/pull/384, thanks again @BrentOnRails !

**Pull request closed without merging**
