### PR TITLE
[elastic] Add config flags for shard level metrics

### PR DESCRIPTION
**Pull request by elafarge**
Tested with test-kitchen.

### CODE REVIEW

**Comment by elafarge** [comment]
WARNING: Since these changes will only be shipped with the 5.5 release of the Agent it might be better to wait for the release before merging that.

**Comment by miketheman** [comment]
@elafarge Can you add some docs to the example? https://github.com/DataDog/chef-datadog/blob/etienne/add-new-es-flags/recipes/elasticsearch.rb#L14-L17

**Comment by elafarge** [comment]
Done @miketheman ! I squashed my changes with the previous commit (I'm not a big fan of `Fixed typo` or `Added doc` commit messages :) ).

**Comment by miketheman** [comment]
@elafarge Thanks! You might want to address the failures before we merge this.

**Comment by elafarge** [comment]
Sorry about that @miketheman , I did this edit on a Windows machine where I didn't have my VIM hooks setup :/ We're finally green now :)

**Comment by miketheman** [comment]
Thanks @elafarge !

**Pull request closed without merging**
