### PR TITLE
Adding a datadog::consul recipe to monitor Consul

### PR DESCRIPTION
**Pull request by wk8**
Thanks for adding Consul in dd-agent 5.5!

### CODE REVIEW

**Comment by darron** [comment]
:+1: 

@miketheman Anything else we should add?

**Comment by wk8** [comment]
@darron @miketheman : Had time to look over this? :)

**Comment by miketheman** [comment]
@wk8 I haven't had a chance yet - been out at a conference. Hope to come back to this soon. I'm also looking to establish quicker, simpler, ChefSpec spec tests for templates.

**Comment by wk8** [comment]
Sounds good, thanks :-)

**Comment by miketheman** [comment]
Thanks @wk8 & @darron !

**Comment by wk8** [comment]
Thank you!

**Pull request merged**
