### PR TITLE
Add min_collection_interval option to ssh_check config

### PR DESCRIPTION
**Pull request by nilskuehme**
Added the option ```min_collection_interval``` to get the possibility to add another interval as 15 seconds to the ssh check config in ```conf.d/ssh_check.d/conf.yaml```.

### CODE REVIEW

**Comment by nilskuehme** [comment]
It looks like there are problems with circleci:
```Upgrading the RVM installation in /opt/circleci/.rvm/
chown: changing group of '/opt/circleci/.rvm/man/man1/rvm.1': Operation not permitted
    could not set group of '/opt/circleci/.rvm/man/man1/rvm.1', prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
chown: changing group of '/opt/circleci/.rvm/man/man1/rvm.1.gz': Operation not permitted
    could not set group of '/opt/circleci/.rvm/man/man1/rvm.1.gz', prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
    Found 22971 files not belonging to 'rvm',
use `--debug` to see the list, run `rvmsudo rvm get stable` to fix it., prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
    Found 3006 directories with mode different than '775',
use `--debug` to see the list, run `rvmsudo rvm get stable` to fix it., prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
    Found 284 files with mode different than '664' or '775',
use `--debug` to see the list, run `rvmsudo rvm get stable` to fix it., prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
Upgrade of RVM in /opt/circleci/.rvm/ is complete.
```

Not sure what I can de here :thinking:

**Comment by amenasria** [comment]
Hey @nilskuehme, thanks again for your PR ! 😊

About your CircleCI tests failing, after some investigation I think it might be because your branch on your fork is 14 commits behind main. Commit [60c3663](https://github.com/nilskuehme/chef-datadog/commit/60c36631449341281c3af2ecdab3685cfcb73734) updated CircleCI (see [this PR](https://github.com/DataDog/chef-datadog/pull/846)) and it may have fixed this issue.

So you should try rerunning the tests after updating it !

**Comment by nilskuehme** [comment]
Hi @amenasria,

oh really? :smile: Yeah will update the PR to not be 14 commits behind it. 

> So you should try rerunning the tests after updating it !
Yeah will do :smiley: 

Thanks for your comment

**Comment by nilskuehme** [comment]
Hi @amenasria,

aah it looks better now. 

It seems kithcen is failing based on:
```
STDERR: The command '/bin/sh -c apt-get install -y sudo openssh-server curl lsb-release' returned a non-zero code: 100
```
for Centos 6.

**Comment by amenasria** [comment]
Hey @nilskuehme, sorry for the delay, lot of work going on, I'm currently trying to fix the CI. Will keep you updated as soon as it's done !

**Comment by nilskuehme** [comment]
Hi @amenasria,

great, thank you very much for your reply.

**Comment by amenasria** [comment]
Hey @nilskuehme sorry for all the time, but the CI is finally fixed !! 🎉🥳

You should merge main into your branch so that we can have these tests all green !

**Review by amenasria — APPROVED** [review]
LGTM ! Thanks for your contribution again !

**Comment by nilskuehme** [comment]
Thank you for all your hard work as well @amenasria! Great that the CI has been fixed finally :partying_face: :party :smile:

**Pull request merged**
