### PR TITLE
Added the option to enable USM

### PR DESCRIPTION
**Pull request by guyarb**
### What does this PR do?
Added the option to enable USM

### Motivation
enabling USM

### CODE REVIEW

**Review by cswatt — APPROVED** [review]

**Review by bkabrda — APPROVED** [review]
Approved, but please hold off merging until we get the kitchen tests fixed and we can run them on your PR.

**Comment by guyarb** [comment]
> Approved, but please hold off merging until we get the kitchen tests fixed and we can run them on your PR.

@bkabrda did the kitchen test fail due to my changes?

**Comment by bkabrda** [comment]
@guyarb no, they're broken because of unrelated dependency upgrade. We'll fix the tests and if it's ok with you, then we'll rebase your branch to get the tests run and merge it if everything succeeds.

**Comment by bkabrda** [comment]
Oh wait, this is a PR from a fork... So we'll notify you when we fix main and ask you to rebase yourself, because we can't rebase branch in your fork.

**Comment by amenasria** [comment]
Hey @guyarb, sorry for the delay. The CI is now fixed (see #880) !

Please rebase your fork so that we can review again your PR.

**Comment by guyarb** [comment]
@amenasria can you merge the PR?

**Pull request merged**
