### PR TITLE
add support for tags

### PR DESCRIPTION
**Pull request by stensonb**

### CODE REVIEW

**Comment by olivielpeau** [comment]
Hi @stensonb, thanks for this addition.

Your change looks good, but could you add a spec test on the etcd recipe? (you can take https://github.com/DataDog/chef-datadog/blob/v2.4.0/spec/integrations/postgres_spec.rb as a reference)

If you don't have time let us know and we'll take care of it, thanks!

**Comment by stensonb** [comment]
is `spec/integrations` where you want it, or should i modify the existing `test/integration/datadog_etcd/serverspec/etcd_spec.rb`

**Comment by olivielpeau** [comment]
`spec/integrations` is where it should live, thanks :)

**Comment by stensonb** [comment]
done! :)

**Comment by olivielpeau** [comment]
Looks good, thanks!

We'll include this in the next minor release.

**Pull request merged**
