### PR TITLE
direct recipe support for sqlserver configuration

### PR DESCRIPTION
**Pull request by smpilo**
This update would allow you to use recipe['datadog::sqlserver'] and configure both instances and custom_metrics.

### CODE REVIEW

**Comment by olivielpeau** [comment]
Hi @smpilo and thanks for opening this PR!

I don't think using a new attribute (`custom_metrics`) on the provider is the right approach here since `custom_metrics` is specific to this check and is part of the `init_config` in the check configuration.

Could you use the existing `init_config` attribute instead? (which means that the resource would be passed `node['datadog']['sqlserver']['init_config']` and that the template would test the existence of the `custom_metrics` key in `init_config` to determine whether to add them or not).

Let me know what you think, and thanks again for contributing!

**Comment by smpilo** [comment]
Sure, I can see that.

I’ll take a look, thanks!

Shane

**Comment by mlcooper** [comment]
@smpilo @olivielpeau I think this one should be able to be closed since #425 was merged

**Comment by olivielpeau** [comment]
That's right @mlcooper, thanks, closing this one

**Comment by smpilo** [comment]
@mlcooper Sweet, thanks 👍

**Pull request closed without merging**
