### PR TITLE
Fixes for dealing with ddagent.exe under windows service.

### PR DESCRIPTION
**Pull request by rorysavage77**
The current datadog dd-agent recipe does not restart the Windows Service 'DatadogAgent' well.  It seems to be that the ddagent.exe (executable) is not responsive to SC commands.   So, I have put in a crude fix to taskkill the service.   I understand it's not the best approach but my changes actually work.

### CODE REVIEW

**Comment by miketheman** [comment]
Hi @rcsavage ! Thanks for taking the time to make the changes, and I'm sorry it hasn't been 100% what you've been expecting.

I'm going to :-1: a few changes in this commit range outright.

1. You change the metadata.rb to yourself as maintainer - I don't think that's accurate for this project. I also ask that contributors not change the version number - as that's part of our release cycle, as can be seen in the repo's CHANGELOG.

2. All the associated Gemfiles that are part of the test suite have been modified for some reason, and they should not have been. Can you elaborate on that at all?

3. As for this changeset applying to Windows Agents, there's modifications to the `_install_linux.rb` recipe - can you explain those?

Again, I want to thank you for your time to contribute this, but there's a few of unexplained changes here that make this change unclear.

**Comment by rcsavage** [comment]
To be quiet honest, I did not expect you to approve my changes outright.   I wanted you to look at the dd-agent recipe a bit closer and see what I have had to do to work around the actual problem with the ddagent.exe.   The problem is not to much with the recipe, the problem is with the ddagent.exe not responding properly to service calls such as 'stop', 'start', etc.   It's the actual dd-agent and not so much the recipe.   My changes are a messy work around to deal with this problem until the ddagent.exe is fixed.   Now that I got your attention, you might want to share that info with your developers.

**Comment by miketheman** [comment]
Tagging @remh and @olivielpeau for Windows Agent service controls.

**Comment by AliDatadog** [comment]
Closed for inactivity

**Pull request closed without merging**
